config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  get '/admin' => 'session#check_session'

  get '/admin/login' => 'session#login', as: 'login'

  delete '/admin/logout' => 'session#logout', as: 'logout'

  post 'admin/authentificate' => 'session#authentificate', as: 'authentificate'

  resources :experiences, path: 'experiencia', only: [:show, :update,:destroy]
  scope '/admin' do
    resources :experiences, except: [:show,:update,:destroy]
  end

  get '/experiencia' => 'statics#experiences', as: 'experiencia'

  post '/mail' => 'statics#mail', as: 'mail'

  root 'statics#landing'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/experience.rb
class Experience < ActiveRecord::Base

	has_many :photos
	
 	accepts_nested_attributes_for :photos, :allow_destroy => true

 	validates :title, presence: true
 	validates :description, presence: true
  validates :date, presence: true
  validates :place, presence: true
end

app/models/medium.rb
class Medium < ActiveRecord::Base

	belongs_to :experience

	has_attached_file :file

	do_not_validate_attachment_file_type :file
	
end

app/models/photo.rb
class Photo < ActiveRecord::Base

	belongs_to :experience

	has_attached_file :file, {
    :preserve_files => "false"
}

	do_not_validate_attachment_file_type :file
	
end

app/models/user.rb
class User < ActiveRecord::Base
	
	attr_accessor :password

	before_save :encrypt_password

	validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 80} 

	validates :password, confirmation: true;

	validates :password_confirmation, presence: true;


	def self.authentificate(email,password)

		user = find_by_email(email.downcase)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		end
		#If theres no user with that email or the password is incorrect this method returns nil
	end


	def encrypt_password
		if password.present?
      		self.password_salt = BCrypt::Engine.generate_salt
      		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    	end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController  
  layout 'layout_exp'

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  layout "layout_admin"

  before_action :set_experience, only: [:show, :edit, :update, :destroy]
  before_action :check_permission, except: [:show]
  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
    render :layout => 'layout_exp'
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: "La experiencia ha sido creada. " }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /experiences/1
  def update
    respond_to do |format|
      if @experience.update(experience_params)

        format.html { redirect_to @experience, notice: 'Se han guardado los cambios.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /experiences/1
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'La experiencia fue destuida exitosamente.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:title, :description, :place , :date, :sphere, photos_attributes: [:id,:file,:description,:_destroy])
    end

    def check_permission
      if current_user.nil?
        redirect_to login_url, alert: 'Por favor inicia sesión' 
      end
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  layout false
  
  def login
    
  end

  def check_session
    if current_user.nil?
      redirect_to login_url
    else
      redirect_to experiences_url
    end
  end

  def authentificate
    email = authentification_params[:email]
    password = authentification_params[:password]

    user = User.authentificate(email,password)

    unless user.nil?
      session[:user_id] = user.id
      redirect_to experiences_url
    else

      redirect_to login_url, :alert => "El usuario o la contraseña no son correctos."
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_url
  end

  private #_________________________________Private:

  def authentification_params
    params.permit(:email, :password)
  end

  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :set_variables

def experiences
  render :layout => 'layout_exp'
end

def mail
  #render :nothing => true
  nom = params[:nombre]
  corr = params[:correo]
  men = params[:mensaje]
  unless nom.empty? or corr.empty? or men.empty?
    ContactMailer.send_mail(nom,corr,men).deliver
  else
    render js: "alert('Por favor complete todos los campos.'); normalSubmit();"
    return
  end
  render plain: "aceptado"
end

private
  def set_variables
    @experiences = Experience.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
 		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
  
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper


  def iframe_from_experience(exp)
    iframe = ""
    unless exp.sphere.nil?
      str1_markerstring = "<iframe"
      str2_markerstring = "</iframe>"
      theres_iframe = exp.sphere[/#{str1_markerstring}(.*?)#{str2_markerstring}/m, 1]
      iframe = exp.sphere.strip unless theres_iframe.nil?
    end

    if iframe.empty?
      style = "<style> .gallery-top{ height:85% !important; } .iframe-container{ display:none; } </style>"
    else
      style = "<style> .gallery-top{ height:45% !important; } .iframe-container{ height:40%;!important } </style>"
      iframe.strip!
      style = style + iframe      
    end
    style.html_safe
  end

	def echo_spacers(number)
		result = ''
		number.times { result+='<div class="spacer"></div>' }
		result.html_safe
	end

	def animation_options(flash)
		if flash.empty?
			'animated fadeIn'
		else
			''
		end
	end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
  def photo_from_experience(exp)
    if exp.photos.any?
      exp.photos.first.file
    else
      image_url("no-image.png")
    end
  end
end

app/views/experiences/_form.html.erb
<% if @experience.errors.any? %>
    <div id="experience-form-error">
      <% @experience.errors.full_messages.each do |message| %>
        <%= message %> <br>
      <% end %>
    </div>
<% end %>
<%= form_for(@experience,  :html => {:id => "experience-form", :multipart => true} ) do |f| %>

  <div id="experience-form-text-data">

    <div class='text-field-container'>
      <%= f.text_field :title, :placeholder => 'Título' %>
    </div>
    <div class="multi-field">
      <%= f.text_field :place, placeholder: 'Lugar' %>
      <%= f.text_field :date, placeholder: 'Fecha' %>  
    </div>
    <div class="text-area-container">
      <%= f.text_area :description, :placeholder => 'Descripción'  %>
    </div>
    <div class='text-field-container'>
      <%= f.text_field :sphere, :placeholder => 'iframe' %>
    </div>


  </div>
  <h2>Galería</h2>
  <div id="experience-form-media-data">

    <%= link_to "Agregar foto", "#" , id: 'photo-adder'%>

    <div id="experience-form-photos">

      <%= f.fields_for :photos do |p| %>
        <div class='photo-as-list'>
          <img id="img-tag" src='<%= p.object.file %>'>
          <div class='remove-existent'>
            <%= p.hidden_field :_destroy %>
          </div>
          <div class='photo-options'>
            <%= p.file_field :file, accept: "image/png,image/gif,image/jpeg" ,class: 'file-field'%>
          </div>
        </div>
      <% end %>
      <%= echo_spacers(4) %>
    </div>
    <%# link_to edit_mode ? 'Eliminar Experiencia' : 'Cancelar' ,"asdas", :id => 'preview-experience' %>
    <%= f.submit edit_mode ? 'Guardar cambios' : 'Crear Experiencia' , :id => 'submit-experience' %>
  </div>
<% end %>

app/views/experiences/_medium_fields.html.erb
<div class='photo-as-list nested-fields'>

	<%= f.file_field :file , accept: 'image/png,image/gif,image/jpeg' , :class => 'custom-file-input'%>
  <%= link_to_remove_association "X", f ,id: 'remove-photo' %>

</div>

app/views/experiences/edit.html.erb
<div class="page-experiences">
<h1>Editar experiencia</h1>

  <%= render 'form' , edit_mode: true %>
</div>

<%# link_to 'Show', @experience %>
<%# link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<div class="page-experiences">
<%= link_to 'Agregar experiencia', new_experience_path, :id =>'new-experience' %>
  <div id="experiences">

    <% @experiences.reverse.each do |exp| %>
      <div class="experience-as-list">
        <div class="info-static">
          <div class="title"><%= exp.title %></div>
          <div class="place"><%= exp.place %></div>
        </div>
        <div class="buttons">
          <%= link_to 'Ver', exp %>
          <%= link_to 'Editar', edit_experience_path(exp) %>
          <%= link_to 'Eliminar', exp, method: :delete, data: { confirm: 'Esta acción no puede deshacerse ¿Está seguro que desea eliminar este elemento?' } %>
        </div>
        <div class="image" style="background-image: url(' <%= photo_from_experience(exp) %> ')" data-main-exp-link='<%= edit_experience_path(exp) %>'></div>
      </div>
    <% end %>
      <!-- SPACERS -->
    <%= echo_spacers(4) %>
  </div>

</div>

app/views/experiences/new.html.erb
<div class="page-experiences">
<h1>Agregar experiencia</h1>

  <%= render 'form' , edit_mode: false %>
</div>

app/views/experiences/show.html.erb
<section id="page-section-show-experience">
  <div class="left-column">
    <div class="content">
     <% flash.each do |name, msg| %>
      <%= content_tag :div, :id => "flash-notice" do %>
        <%= msg %>
        <%= link_to("Volver a editar", edit_experience_path(@experience) ) %>
      <% end %>
    <% end %> 
      <h3><%= @experience.date %></h3>
      <h1><%= @experience.title %></h1>
      <h2><%= @experience.place %></h2>
      <p><%= @experience.description %></p>

      <%= link_to("Toda la expeiencia", experiencia_path, id:'all-experience-button') %>
    </div>
  </div>
  
  <div class="right-column">
    <!-- Swiper -->
    <div class="iframe-container">
      <%= iframe_from_experience(@experience) %>
    </div>
    <div class="swiper-container gallery-top">
        <div class="swiper-wrapper">
          <% @experience.photos.each do |photo| %>
            <div class="swiper-slide" style="background-image:url(<%=photo.file%>)"></div>
          <% end %>
        </div>
        <!-- Add Arrows -->
        <div class="swiper-button-next swiper-button-white"></div>
        <div class="swiper-button-prev swiper-button-white"></div>
    </div>
    <div class="swiper-container gallery-thumbs">
        <div class="swiper-wrapper">
          <% @experience.photos.each do |photo| %>
            <div class="swiper-slide" style="background-image:url(<%=photo.file%>)"></div>
          <% end %>
        </div>
    </div>

    <!-- Swiper JS -->

    <!-- Initialize Swiper -->
    <script>
    var appendNumber = 4;
    var prependNumber = 1;
    var galleryTop = new Swiper('.gallery-top', {
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        spaceBetween: 10,
        keyboardControl: true,
    });
    var galleryThumbs = new Swiper('.gallery-thumbs', {
        spaceBetween: 10,
        centeredSlides: true,
        slidesPerView: 'auto',
        touchRatio: 0.2,
        slideToClickedSlide: true
    });
    galleryTop.params.control = galleryThumbs;
    galleryThumbs.params.control = galleryTop;
    </script>
  
  </div>


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VHDA Servicios Integrales de Ingeniería</title>

  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <meta name="description" content="Somos una empresa mexicana, que busca que el gasto en obras públicas sea eficiente y logre el mayor beneficio a las sociedades. Esto lo logramos con proyectos integrales, desde planeación de presupuestos, a consultoría en el desarrollo de la obra.">
  <meta name="keywords" content="VHDA, vhda, infraestructura, servicios integrales de ingeniería, servicios integrales de ingenieria, asesoría a municipios, elaboración de expedientes técnicos, topografía, dirección responsable de obra,mantenimiento y rehabilitación">

  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-64717188-1', 'auto');
    ga('send', 'pageview');
  </script>
</head>
<body>

  <div id="nav-logo-container">
    <div id="ribbon">
      <div id="logo"></div>
      <svg viewBox="0 0 10 10" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
        <polygon points="0,0 0,9 5,10 10,9, 10,0"/>
      </svg>
    </div>
  </div>

<div id="nav-bar">
  <div id="nav-bar-mobile">
      <div class="current-tab"></div>
      <svg id="nav-button"></svg>
  </div>
  <a href="/" id="mini-logo" ></a>
  <nav id="nav-tabs-container" class="animated fadeIn smooth">
    <%= link_to("Servicios", "#page-section-2 h1") %>
    <%= link_to("Nosotros", "#page-section-3") %>
    <%= link_to("Experiencia", "#page-section-4") %>
    <%= link_to("Contacto", "#page-section-5") %>
  </nav>

</div>

<%= yield %>
<footer>
  <div>
    <p>VHDA© 2015 </p>
    <a href="http://www.ment.com.mx" class="logo-ment"></a> 
  </div>
</footer>
</body>
</html>

app/views/layouts/layout_admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VHDA - Sistema Administrador</title>

  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div id="nav-logo-container">
    <%= link_to experiences_path, id: 'mini-ribbon' do %>
      <div id="logo"></div>
      <svg viewBox="0 0 10 10" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
        <polygon points="0,0 0,9 5,10 10,9, 10,0"/>
      </svg>
    <% end %>
  </div>

<div id="mini-nav-bar">
  <div id="nav-bar-mobile">
      <div class="current-tab"></div>
      <svg id="nav-button"></svg>
  </div>
  <nav id="nav-tabs-container" class="animated fadeIn">
    <%= link_to "Toda la experiencia",experiences_path %>
    <%= link_to("Cerrar sesión", logout_path, method: :delete ) %>
  </nav>
  
</div>
	<%= yield %>

</body>
</html>

app/views/layouts/layout_exp.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>

  <title>Experiencia</title>
  
</head>
<body>

<div id="nav-bar-exp">
  <div id="nav-bar-mobile">
      <div class="current-tab"></div>
      <svg id="nav-button"></svg>
  </div>
  <a href="/" id="mini-logo" ></a>
  <nav id="nav-tabs-container" class="animated fadeIn">
    <%= link_to("Servicios", root_path + "#page-section-2") %>
    <%= link_to("Nosotros", root_path + "#page-section-3") %>
    <%= link_to("Experiencia", root_path + "#page-section-4") %>
    <%= link_to("Contacto", root_path + "#page-section-5") %>
  </nav>
</div>

  <%= yield %>
</body>
</html>

app/views/session/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">

 <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <title>VHDA - Sistema Administrador</title>
</head>
<body>

<%= form_tag authentificate_url ,autocomplete: 'off', id: 'login-form' ,class: animation_options(flash) do %>

  <div id="login-logo"></div>

  <div id="login-greet">Sistema administrador</div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash-#{name}" , class: 'animated shake' %>
  <% end %> 

  <div id='login-fields'>
    <%= text_field_tag :email, nil, autocomplete: 'off',placeholder: 'E-mail', class: "login-field" %>
    <div class="spacer"></div>
    <%= password_field_tag :password, nil , placeholder: 'Password', class: "login-field" %>
  </div>

  <%= submit_tag 'Iniciar sesión', id: 'login-button' %>

<% end %>
  
</body>
</html>

app/views/statics/experiences.html.erb
<section id="experiences-page">

<div class="column">
  <h1>Nuestra experiencia.</h1>
  <h2>Proyectos terminados y <br> casos de éxito.</h2>
</div>

<div id="experiences">
  <% @experiences.reverse.each do |exp| %>
    <%= link_to exp , class: 'experience-as-list' do %>
      <div class="info">
        <div class="title"><%= exp.title %></div>
        <div class="place"><%= exp.place %></div>
        <hr><div class="date"><%= exp.date %></div>
      </div>
      
      <div class="image" style="background-image: url(' <%= photo_from_experience(exp) %> ') "></div>
    <% end %>
  <% end %>
    <!-- SPACERS -->
  <%= echo_spacers(4) %>

</div>

</section>

app/views/statics/landing.html.erb
<section id="page-section-1">
  <div class="page-image-background"></div>
  <div class="page-color-overlay">
    <div class="centered">
      <h1 class="animated fadeIn">Servicios Integrales de Ingeniería</h1>
      <h2 class="animated fadeIn">Civil, conceptual, de detalle, construcción, estudios y consultoría.</h2>
    </div>
  </div>
      <svg id="arrow" class="animated infinite pulse" viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg">
      <polyline points="1,4 5,8 9,4" />
    </svg>
</section>

<!-- ****************************************** Servicios ***************************************** -->

<section id="page-section-2">
  <svg class="poly-background" preserveAspectRatio="none" viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" version="1.1">
      <g>
         <clipPath id="poly-mask">
            <polygon points="0,0 0,10 10,10 10,0 5,1" />
         </clipPath>
      </g> 
  
      <rect class="left" clip-path="url(#poly-mask)" width="50%" height="100%" />
      <rect class="right" clip-path="url(#poly-mask)" x="50%" width="50%" height="100%" />
  </svg>

  <div class="left-column">
    <div class="content">
      <h1><span>Proyectos</span> arquitectónicos y de ingeniería.</h1>
      <div class="animated-image"></div>
      <p>
        <span>Vías terrestres:</span> <br> Caminos, puentes, pavimentación, terracerías
        <br>
      </p>
        <p><span>Infraestructura hidráulica y de saneamiento:</span> Agua potable, alcantarillado pluvial y sanitario, plantas de tratamiento residuales
        <br>
      </p>
      <p>
        <span>Espacios</span> públicos, deportivos y culturales
        <br>
        <span>Vivienda</span> y otros.
      </p>
    </div>
  </div>
  <div class="right-column">
    <div class="content">
      <h1><span>Asesoría</span> técnica y consultoría.
      </h1>
      <div class="animated-image"></div>
      <p><span>Asesoría a municipios</span>, elaboración de expedientes técnicos, topografía, dirección responsable de obra, <span>mantenimiento y rehabilitación</span>, presupuestos.</p>
    </div>
  </div>
</section>

<!-- ****************************************** Nosotros ***************************************** -->

<section id="page-section-3">
<div class="page-image-background"></div>

  <div id="us">
    <div class="centered">
      <h1>Nosotros.</h1>
      <p>Somos una empresa mexicana, que busca que el gasto en obras públicas sea eficiente y logre el mayor beneficio a las sociedades. Esto lo logramos con proyectos integrales, desde planeación de presupuestos, a consultoría en el desarrollo de la obra.</p>
    </div>
  </div>

  <svg class="poly-background" preserveAspectRatio="none" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" version="1.1">
      <polygon points="0,5 0,20 20,20 20,6.8" />
  </svg>

  <div id="mision">
    <h2>Misión</h2>
    <div class="centered">
      <p>Ser una empresa competitiva a nivel estatal que ejecute proyectos integrales enfocados a lograr la satisfacción de nuestros clientes, empleados y sociedad beneficiada.</p>
    </div>
  </div>

  <div id="vision">
    <h2>Visión</h2>
    <div class="centered">
      <p>Desarrollar proyectos rentables fundamentados en la capacidad técnica de la empresa y el personal altamente preparado, que trabaje con ética profesional, calidad y seguridad, proporcionando certeza y valor agregado a nuestros clientes. </p>
    </div>

  </div>

  <div id="values">
    <div class="centered">
      <h2>Valores</h2>
      <p>
        <span>Trabajo en equipo</span>
        <span>Mejora continua</span>
        <span>Desarrollo de estado</span>
        <span>Seguridad</span>
        <span>Calidad</span>
        <span>Tecnología</span>
        <span>Desarrollo Integral</span>
        <span>Rentabilidad</span>
      </p>
    </div>
  </div>

</section>

<!-- ****************************************** Experiencia ***************************************** -->

<section id="page-section-4">

  <div class="left-column">
    <div class="color-overlay">
      <div class="content">
        <h1>Nuestra experiencia.</h1>
        <h2>Proyectos terminados y <br> casos de éxito.</h2>
        <%= link_to("Toda la experiencia", experiencia_path, id:'all-experience-button') %>
      </div>
    </div>
  </div>

  <div class="right-column">
    <div id="experiences">
      <% @experiences.reverse.take(6).each do |exp| %>
        <%= link_to exp , class: 'experience-as-list' do %>
          <div class="info">
            <div class="title"><%= exp.title %></div>
            <div class="place"><%= exp.place %></div>
            <hr><div class="date"><%= exp.date %></div>
          </div>

          <div class="image" style="background-image: url(' <%= photo_from_experience(exp) %> ') "></div>
        <% end %>
      <% end %>
    </div>
    <%= link_to("Toda la expeiencia", experiencia_path, id:'all-experience-button-mobile') %>
  </div>

</section>

<!-- ****************************************** Contacto ***************************************** -->

<section id="page-section-5">

<div class="page-image-background"></div>

  <div id="contact-info">
    <div class="content centered">
      <h1>Contacto.</h1>
      <p><span>2da.</span> Privada de Independencia No. <span>102</span>,<br>
      San Agustín de las Juntas, Oaxaca. <br>
      C.P. <span>71238</span>
      </p>
      <br>
      <p>Teléfono: (951) 143 8471</p>
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1907.6449081630874!2d-96.70970193685645!3d17.009448539208698!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTfCsDAwJzM0LjIiTiA5NsKwNDInMzQuMyJX!5e0!3m2!1sen!2smx!4v1425967848184" style="border:0"></iframe>    
      </div>
  </div>
  <aside id="contact-panel">
    <div class="centered">
      <h2>Escríbenos un <br> mensaje.</h2>
      <%= form_tag mail_path, method: :post, remote: true, id:'mail-form' do %>
        <%= text_field_tag :nombre ,nil, placeholder:'Nombre', class:"contact-text"  %>
        <%= email_field_tag :correo ,nil, placeholder:'Correo electrónico', class:"contact-text"  %>
        <%= text_area_tag :mensaje ,nil, rows: "6", placeholder:'Mensaje', class:'contact-text-area' %>
        <%= submit_tag "Enviar", class: 'submit' %>
      <% end %>
    </div>

  </aside>

</section>